[install]
# Automatically install dependencies when running scripts
auto = "bun"

# Install dependencies only in current directory
# Don't install in parent directories
scopes = false

# Use exact versions by default
exact = false

# Registry configuration
registry = "https://registry.npmjs.org/"

[run]
# Enable shell completion
shell = true

# Set environment variables
env = []

[test]
# Test configuration for Bun
root = "./src"
preload = []

# Coverage settings
coverage = true
coverageThreshold = 80
coverageReporter = ["text", "html"]

# Test timeout in milliseconds  
timeout = 5000

[build]
# Build target
target = "bun"

# External packages (don't bundle these)
external = []

[dev]
# Development server settings
# These are used when running `bun --watch`
hot = true
port = 3000