services:
  # PostgreSQL Database
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hono_skeleton
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Valkey Cache (Redis-compatible)
  valkey:
    image: valkey/valkey:8-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  # Hono API Service
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_URL=postgres://postgres:postgres@postgres:5432/hono_skeleton
      - VALKEY_HOST=valkey
      - VALKEY_PORT=6379
      - JWT_SECRET=your-production-jwt-secret
      - JWT_EXPIRES_IN=1h
      - PORT=3000
      - HOST=0.0.0.0
    depends_on:
      postgres:
        condition: service_healthy
      valkey:
        condition: service_healthy
    restart: unless-stopped

  # Database migrations (run once)
  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_URL=postgres://postgres:postgres@postgres:5432/hono_skeleton
    depends_on:
      postgres:
        condition: service_healthy
    command: ["bun", "run", "db:migrate"]
    restart: "no"

volumes:
  postgres_data: