version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=file:./dev.db
      - JWT_SECRET=development_jwt_secret
      - JWT_EXPIRES_IN=24h
      - CORS_ORIGIN=*
    volumes:
      - ./dev.db:/app/dev.db
    depends_on:
      - postgres
    networks:
      - hono-network

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=hono_skeleton
      - POSTGRES_USER=hono_user
      - POSTGRES_PASSWORD=hono_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hono-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - hono-network

volumes:
  postgres_data:
  redis_data:

networks:
  hono-network:
    driver: bridge