version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://hono_user:hono_password@postgres:5432/hono_skeleton
      - JWT_SECRET=development_jwt_secret
      - JWT_EXPIRES_IN=24h
      - CORS_ORIGIN=*
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - hono-network

  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: hono_skeleton
      POSTGRES_USER: hono_user
      POSTGRES_PASSWORD: hono_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hono_user -d hono_skeleton"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - hono-network

volumes:
  postgres_data:

networks:
  hono-network:
    driver: bridge