# GitHub Actions workflow for CI/CD pipeline
name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bun-version: ['1.x'] # Use '1.x' for latest Bun 1.x version

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ matrix.bun-version }}

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run Lint
        run: bun run lint

      - name: Run Format Check
        run: bun run format:check

      - name: Run Unit Tests
        run: bun run test:unit

      - name: Run Integration Tests
        run: bun run test:integration

      - name: Build Docker Image
        run: docker build -t hono-skeleton:$(echo $GITHUB_SHA | head -c 7) .